name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day
  workflow_dispatch:      # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: RzRagnarok
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: Push Snake to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          target_branch: output
          build_dir: dist
